##############################
# App Definition
app: syrin-webhook
component: webhook
core: syrin
version: 1.0.18

##############################
# Definition of the Deployment
deployment:
  replicas: 1
  revisionHistoryLimit: 3
  sendlogs: "true"
  stack: syrin
  lbtype: internal
  affinity:
    - apps: services
  # imagePullSecrets: 
  #   - name: ocirsecret-mutantrogue
  containers:
    - name: syrin-webhook
      image: ghcr.io/syrin-alert/
      ports:
        name: "sa"
        number: 80
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "1"
      env:
        - name: TZ
          value: "America/Sao_Paulo"

# ###########################
# # Definition of the Service
# services:
#   - name: svc-syrin-webhook
#     type: ClusterIP
#     selector:
#       app: syrin-webhook
#       component: syrin
#     ports:
#       - name: syrin-webhook-tcp
#         port: 80
#         targetPort: 80
#         protocol: TCP

#   - name: svce-syrin-webhook
#     type: NodePort
#     selector:
#       app: syrin-webhook
#       component: syrin
#     ports:
#       - name: syrin-webhook-tcp
#         nodePort: 30007
#         port: 80
#         targetPort: 80
#         protocol: TCP
