##############################
# App Definition
app: syrin-webhook
component: webhook
core: syrin
version: 1.0.18

##############################
# Definition of the Deployment
deployment:
  replicas: 1
  revisionHistoryLimit: 3
  sendlogs: "true"
  stack: syrin
  lbtype: internal
  affinity:
    - apps: services
  containers:
    - name: syrin-webhook
      image: ghcr.io/syrin-alert/
      ports:
        name: "sa"
        number: 80
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "1"
      env:
        - name: TZ
          value: "America/Sao_Paulo"
        - name: PORT
          value: "80"
        - name: SERVICE_K8S
          value: "oke"
        # rabbitmq
        - name: RABBITMQ_HOST
          value: "svc-rabbitmq.rabbitmq.svc.cluster.local"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_VHOST
          value: "syrin"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: s-rabbitmq
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: s-rabbitmq
              key: RABBITMQ_DEFAULT_PASS

###########################
# Definition of the Service
services:
  - type: ClusterIP
    selector:
      app: syrin-webhook
      component: webhook
    ports:
      - name: syrin-webhook-tcp
        port: 80
        targetPort: 80
        protocol: TCP

  - type: NodePort
    selector:
      app: syrin-webhook
      component: webhook
    ports:
      - name: syrin-webhook-tcp
        nodePort: 30008
        port: 80
        targetPort: 80
        protocol: TCP
